final_project/urls.py
from django.contrib import admin
from django.urls import path, re_path
from app.views import TestView, GenerateArrSCR, ScheduleArrView
from cashmanage.views import StartPage, ListAccountView, ListEntryView, CreateEntryView, \
    UpdateEntryView, load_subcategories, StatsView, CategoryListView, DeleteEntryView, \
    AddAccountView, EditAccountView, DeleteAccountView, CategoryAddView, DeleteCategoryView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', TestView.as_view()),
    path('arrscr', GenerateArrSCR.as_view()),
    path('schedule', ScheduleArrView.as_view()),
    ############################################
    path('', ListEntryView.as_view(), name='entry_list'),
    path('accounts', ListAccountView.as_view(), name='all_accounts'),
    path('add-account', AddAccountView.as_view(), name='add_account'),
    path('account/<int:pk>', EditAccountView.as_view(), name='edit_account'),
    path('account/delete/<int:pk>', DeleteAccountView.as_view(), name='delete_account'),
    path('entry/<int:pk>', UpdateEntryView.as_view(), name='entry_change'),
    path('add-entry', CreateEntryView.as_view(), name='entry_add'),
    path('entry/delete/<int:pk>', DeleteEntryView.as_view(), name='delete_entry'),
    path('ajax/load-subcat', load_subcategories, name='ajax_load_subcat'),
    path('stats', StatsView.as_view(), name='stats_view'),
    path('categories', CategoryListView.as_view(), name='category_list'),
    path('add-category', CategoryAddView.as_view(), name='add_category'),
    path('categories/delete/<int:pk>', DeleteCategoryView.as_view(), name='delete_category'),
]

cashmanage/models.py
from django.db import models

CHOICES = (
    ('1', 'Wpływ'),
    ('2', 'Wydatek'),
    # ('3', 'Przeksięgowanie')
)


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    name = models.CharField(max_length=128)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=128)
    cash_amount = models.FloatField()

    def __str__(self):
        return self.name


class Entry(models.Model):
    date = models.DateField(auto_now_add=True)
    options = models.TextField(default='2', choices=CHOICES)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, null=True)
    amount = models.FloatField()
    description = models.TextField()

cashmanage/forms.py
from django import forms
from cashmanage.models import *


class AddEntryForm(forms.ModelForm):
    options = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

    class Meta:
        model = Entry
        fields = '__all__'

        def __init__(self):
            super().__init__()
            self.fields['subcategory'].queryset = Subcategory.objects.none()


class UpdateEntryForm(forms.ModelForm):
    options = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

    class Meta:
        model = Entry
        fields = '__all__'

        def __init__(self):
            super().__init__()
            self.fields['subcategory'].queryset = Subcategory.objecst.none()


class AddAccountForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = '__all__'


class AddCategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'

cashmanage/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView, ListView, CreateView, UpdateView, DeleteView
from cashmanage.forms import AddEntryForm, AddAccountForm, UpdateEntryForm, AddCategoryForm
from cashmanage.models import Account, Entry, Subcategory, Category


class StartPage(View):

    def get(self, request):
        return render(request, 'base.html')


class ListAccountView(View):

    def get(self, request):
        accounts = Account.objects.all().order_by('id')
        return render(request, 'ListAccounts.html', {'accounts': accounts})


class ListEntriesView(View):

    def get(self, request):
        entries = Entry.objects.all()
        return render(request, 'EntryList.html', {'entries': entries})


class ListEntryView(View):

    def get(self, request):
        entries = {}
        all = Entry.objects.all().order_by('-date')
        for item in all:
            entries[item.date] = []
        for item in all:
            if item.date in entries:
                entries[item.date].append(item)
        return render(request, 'cashmanage/entry_list.html', {'entries': entries})


class CreateEntryView(CreateView):
    model = Entry
    form_class = AddEntryForm
    success_url = reverse_lazy('entry_list')

    def form_valid(self, form):
        account = form.cleaned_data['account']
        category = form.cleaned_data['category']
        subcategory = form.cleaned_data['subcategory']
        amount = form.cleaned_data['amount']
        description = form.cleaned_data['description']
        options = form.cleaned_data['options']
        if options == '2':
            amount *= -1
        Entry.objects.create(
            account=Account.objects.get(name=account),
            category=Category.objects.get(name=category),
            subcategory=Subcategory.objects.get(name=subcategory),
            amount=amount,
            description=description
        )
        act = Account.objects.get(name=account)
        total = act.cash_amount + amount
        act.cash_amount = total
        act.save()
        return redirect('entry_list')


class UpdateEntryView(View):

    def get(self, request, pk):
        entry = Entry.objects.get(id=pk)
        form = UpdateEntryForm(initial={
            'options': entry.options,
            'account': entry.account,
            'category': entry.category,
            'subcategory': entry.subcategory,
            'amount': entry.amount,
            'description': entry.description
        })
        request.session['old_amount'] = entry.amount
        request.session['old_account'] = entry.account.id
        return render(request, 'cashmanage/update_entry_form.html', {'form': form,
                                                                     'pk': pk})

    def post(self, request, pk):
        form = UpdateEntryForm(request.POST)
        if form.is_valid():
            old_entry = Entry.objects.get(id=pk)
            new_account = form.cleaned_data['account']
            new_amount = form.cleaned_data['amount']
            options = form.cleaned_data['options']
            if options == '2':
                new_amount *= -1
            if request.session['old_account'] != new_account.id:
                old_account = Account.objects.get(id=request.session['old_account'])
                pass
                if request.session['old_amount'] != new_amount:
                    pass
            else:
                difference = abs(request.session['old_amount']) - abs(new_amount)
                new_account.cash_amount += difference

            old_entry.options = options
            old_entry.account = new_account
            old_entry.category = form.cleaned_data['category']
            old_entry.subcategory = form.cleaned_data['subcategory']
            old_entry.amount = new_amount
            old_entry.description = form.cleaned_data['description']
            old_entry.save()
            return HttpResponse(request.session['old_amount'], request.session['old_account'])

# class UpdateEntryView(UpdateView):
#     model = Entry
#     form_class = AddEntryForm
#     success_url = reverse_lazy('entry_list')




class DeleteEntryView(DeleteView):
    model = Entry
    success_url = reverse_lazy('entry_list')



def load_subcategories(request):
    category_id = request.GET.get('category')
    subcategories = Subcategory.objects.filter(category_id=category_id).order_by('name')
    return render(request, 'cashmanage/subcat_dropdown_list_option.html', {'subcategories': subcategories})


class AddAccountView(CreateView):
    model = Account
    form_class = AddAccountForm
    success_url = reverse_lazy('all_accounts')


class EditAccountView(UpdateView):
    model = Account
    form_class = AddAccountForm
    success_url = reverse_lazy('all_accounts')


class DeleteAccountView(DeleteView):
    model = Account
    success_url = reverse_lazy('all_accounts')


class StatsView(View):

    def get(self, request):
        labels = []
        for cat in Category.objects.all():
            labels.append(cat.name)
        data = []
        total = 0
        for lab in labels:
            for item in Entry.objects.all():
                if lab == item.category.name:
                   total += float(item.amount)
            data.append(total)
            total = 0
        ctx = {}
        if len(labels) == len(data):
            for i in range(len(data)):
                ctx[labels[i]] = data[i]
        else:
            return HttpResponse('Coś tu nie gra')
        return render(request, 'stats.html', {'labels': labels, 'data': data, 'ctx': ctx})


class CategoryListView(ListView):

    model = Category


class CategoryAddView(CreateView):
    model = Category
    form_class = AddCategoryForm
    success_url = reverse_lazy('category_list')


class DeleteCategoryView(DeleteView):
    model = Category
    success_url = reverse_lazy('category_list')

templates/cashmanage/account_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
    <p>Czy na pewno chcesz usunąć konto: "{{ object.name }}"?</p>
    <input type="submit" value="Tak" class="btn btn-primary"> <a href="/accounts" class="btn btn-primary">Nie</a>
    </form>
{% endblock %}

templates/cashmanage/account_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
    <button type="submit" class="btn btn-primary">Dodaj Konto</button>
    </form>
{% endblock %}

templates/cashmanage/category_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
    <p>Czy na pewno chcesz usunąć kategorię: "{{ object.name }}"?</p>
    <input type="submit" value="Tak" class="btn btn-primary"> <a href="/accounts" class="btn btn-primary">Nie</a>
    </form>
{% endblock %}

templates/cashmanage/category_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Dodaj kategorię</button>
    </form>
{% endblock %}

templates/cashmanage/category_list.html
{% extends 'base.html' %}
{% block content %}
<div>
    <div align="left"><h1>Kategrie</h1></div>
    <div align="right"><a href="/add-category" class="btn btn-primary">Dodaj kategorię</a></div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Nazwa</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {% for category in object_list %}
    <tr>
      <td>{{ category.name }}</td>
      <td align="right">
          <a href="/categories/{{ category.id }}" class="btn btn-warning" data-id="{{ value2.id }}">Edytuj</a>
          <a href="/categories/delete/{{ category.id }}" class="btn btn-danger" data-id="{{ value2.id }}">Usuń</a>
      </td>
    </tr>

    {% empty %}
    <h1>Brak kategorii</h1>
  {% endfor %}
   </tbody>
</table>
{% endblock %}

templates/cashmanage/entry_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
    <p>Czy na pewno chcesz usunąć "{{ object.get_options_display }} {{ object.amount }}"?</p>
    <input type="submit" value="Tak" class="btn btn-primary"> <a href="/" class="btn btn-primary">Nie</a>
    </form>
{% endblock %}

templates/cashmanage/entry_form.html
{% extends 'base.html' %}
{% block content %}
    <h2>Dodawanie nowego wpisu</h2>
    <form action="#" method="post" id="entryForm" data-subcat-url="{% url 'ajax_load_subcat' %}">
    {% csrf_token %}
        <div class="btn-group btn-group-toggle" data-toggle="buttons">
            {% for radio in form.options %}
                  <label class="btn btn-secondary">
                    {{ radio }}
                  </label>
            {% endfor %}
        </div>
        <table>
            <tr>
                <th>
                    {{ form.account.label }}
                </th>
                <td>
                    {{ form.account }}
                </td>
            </tr>
            <tr>
                <th>
                    {{ form.category.label }}
                </th>
                <td>
                    {{ form.category }}
                </td>
            </tr>
            <tr>
                <th>
                    {{ form.subcategory.label }}
                </th>
                <td>
                    {{ form.subcategory }}
                </td>
            </tr>
            <tr>
                <th>
                    {{ form.amount.label }}
                </th>
                <td>
                    {{ form.amount }}
                </td>
            </tr>
            <tr>
                <th>
                    {{ form.description.label }}
                </th>
                <td>
                    {{ form.description }}
                </td>
            </tr>
        </table>
        <button type="submit" class="btn btn-primary">Dodaj wpis</button>
    </form>
    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <script>
    $('#id_category').change(function(){
        var url = $('#entryForm').attr("data-subcat-url");
        var category = $(this).val();

        $.ajax({
            url: url,
            data: {
                'category': category
            }

        }).done(function (data) {
            $('#id_subcategory').html(data)
        })
    });
    </script>
{% endblock %}

templates/cashmanage/entry_list.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <div align="left"><h2>Wpisy</h2></div>
        <div align="right"><a href="/add-entry" class="btn btn-primary">Dodaj wpis</a></div>
    </div>
        {% for key, value in entries.items %}
           <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">{{ key }}</th>
                  <th scope="col">Konto</th>
                  <th scope="col">Wartość</th>
                  <th scope="col"></th>
                </tr>
              </thead>
            {% for value2 in value %}
              <tbody>
                <tr>
                    <td class="category" data-id="{{ value2.id }}">{{ value2.category }}</td>
                    <td>{{ value2.account.name }}</td>
                    <td class="amount">{{ value2.amount }}</td>
                    <td align="right">
                        <a href="/entry/{{ value2.id }}" class="btn btn-warning" data-id="{{ value2.id }}">Edytuj</a>
                        <a href="/entry/delete/{{ value2.id }}" class="btn btn-danger" data-id="{{ value2.id }}">Usuń</a>
                    </td>
                </tr>
              </tbody>
            {% endfor %}
            </table>
        {% endfor %}
{#    <script#}
{#    src="https://code.jquery.com/jquery-3.4.1.js"#}
{#    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="#}
{#    crossorigin="anonymous"></script>#}
{#    <script>#}
{#    $(function(){#}
{#        console.log($('.category').val());#}
{#        if (parseFloat($('amonut').innerText) > 0) {#}
{#            $('.amount').css({'color': 'green'})#}
{#        }else{#}
{#            $('.amount').css({'color': 'red'})#}
{#        };#}
{#    });#}
{#    </script>#}
{% endblock %}

templates/cashmanage/subcat_dropdown_list_option.html
<option value=""></option>
{% for subcat in subcategories %}
    <option value="{{ subcat.pk }}">{{ subcat.name }}</option>
{% endfor %}

templates/cashmanage/update_entry_form.html
{% extends 'base.html' %}
{% block content %}
    <h2>Edycja wpisu</h2>
    <form action="#" method="post" id="entryForm" data-subcat-url="{% url 'ajax_load_subcat' %}">
    {% csrf_token %}
        <div class="btn-group btn-group-toggle" data-toggle="buttons">
            {% for radio in form.options %}
                  <label class="btn btn-secondary">
                    {{ radio }}
                  </label>
            {% endfor %}
        </div>
        <table>
            <tr>
                <th>
                    {{ form.account.label }}
                </th>
                <td>
                    {{ form.account }}
                </td>
            </tr>
            <tr>
                <th>
                    {{ form.category.label }}
                </th>
                <td>
                    {{ form.category }}
                </td>
            </tr>
            <tr>
                <th>
                    {{ form.subcategory.label }}
                </th>
                <td>
                    {{ form.subcategory }}
                </td>
            </tr>
            <tr>
                <th>
                    {{ form.amount.label }}
                </th>
                <td>
                    {{ form.amount }}
                </td>
            </tr>
            <tr>
                <th>
                    {{ form.description.label }}
                </th>
                <td>
                    {{ form.description }}
                </td>
            </tr>
        </table>
        <button type="submit" class="btn btn-primary">Dodaj wpis</button>
    </form>
    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <script>
    $('#id_category').change(function(){
        var url = $('#entryForm').attr("data-subcat-url");
        var category = $(this).val();

        $.ajax({
            url: url,
            data: {
                'category': category
            }

        }).done(function (data) {
            $('#id_subcategory').html(data)
        })
    });
    </script>
{% endblock %}