final_project/urls.py
from django.contrib import admin
from django.urls import path, re_path
from app.views import TestView, GenerateArrSCR, ScheduleArrView
from cashmanage.views import StartPage, ListAccountView, ListEntryView, CreateEntryView, \
    UpdateEntryView, load_subcategories, StatsView, CategoryListView, DeleteEntryView, \
    AddAccountView, EditAccountView, DeleteAccountView, CategoryAddView, DeleteCategoryView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', TestView.as_view()),
    path('arrscr', GenerateArrSCR.as_view()),
    path('schedule', ScheduleArrView.as_view()),
    ############################################
    path('', ListEntryView.as_view(), name='entry_list'),
    path('accounts', ListAccountView.as_view(), name='all_accounts'),
    path('add-account', AddAccountView.as_view(), name='add_account'),
    path('account/<int:pk>', EditAccountView.as_view(), name='edit_account'),
    path('account/delete/<int:pk>', DeleteAccountView.as_view(), name='delete_account'),
    path('entry/<int:pk>', UpdateEntryView.as_view(), name='entry_change'),
    path('add-entry', CreateEntryView.as_view(), name='entry_add'),
    path('entry/delete/<int:pk>', DeleteEntryView.as_view(), name='delete_entry'),
    path('ajax/load-subcat', load_subcategories, name='ajax_load_subcat'),
    path('stats', StatsView.as_view(), name='stats_view'),
    path('categories', CategoryListView.as_view(), name='category_list'),
    path('add-category', CategoryAddView.as_view(), name='add_category'),
    path('categories/delete/<int:pk>', DeleteCategoryView.as_view(), name='delete_category'),
]

cashmanage/models.py
from django.db import models

CHOICES = (
    ('1', 'Wpływ'),
    ('2', 'Wydatek'),
    # ('3', 'Przeksięgowanie')
)


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    name = models.CharField(max_length=128)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=128)
    cash_amount = models.FloatField()

    def __str__(self):
        return self.name


class Entry(models.Model):
    date = models.DateField(auto_now_add=True)
    options = models.TextField(default='2', choices=CHOICES)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, null=True)
    amount = models.FloatField()
    description = models.TextField()

templates/AddEntry.html
{% extends 'base.html' %}
{% block content %}
    <form action="#" method="post">
    {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
    </form>
    <button type="button" class="btn btn-primary">Dodaj wpis</button>
{% endblock %}

templates/EntryList.html
{% extends 'base.html' %}
{% block content %}
    <h1>test</h1>
    {% for entry in entries %}
        {{ entry }}
    {% endfor %}
    <a href="/add-entry" type="button" class="btn btn-primary">Dodaj wpis</a>
{% endblock %}

templates/ListAccounts.html
{% extends 'base.html' %}
{% block title %}Lista Kont{% endblock %}
{% block content %}
    <div>
        <div align="left"><h2>Konta</h2></div>
        <div align="right"><a href="/add-account" class="btn btn-primary">Dodaj konto</a></div>
    </div>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nazwa</th>
          <th scope="col">Saldo</th>
          <th scope="col" align="right">Akcja</th>
        </tr>
      </thead>
      <tbody>
      {% for account in accounts %}
        <tr>
          <th scope="row">{{ account.id }}</th>
          <td>{{ account.name }}</td>
          <td>{{ account.cash_amount }}</td>
          <td align="right">
              <a href="account/{{ account.id }}" class="btn btn-warning">Edytuj</a>
              <a href="account/delete/{{ account.id }}" class="btn btn-danger">Usuń</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        <header class="page-header">
            <nav class="navbar navbar-expand-lg justify-content-between">
                <a href="/" class="navbar-brand main-logo main-logo-smaller">
                    POWIEDZMY ŻE MONEY MANAGER
                </a>
                <ul class="nav nounderline text-uppercase">
                    <li class="nav-item ml-4">
                        <a class="nav-link" href="/about">o aplikacji</a>
                    </li>
                    <li class="nav-item ml-4">
                        <a class="nav-link" href="/contact">Kontakt</a>
                    </li>
                </ul>
            </nav>
        </header>
        <section>
             <div class="row">
                 <div class="col-3">
                     <ul class="nav flex-column">
                          <li class="nav-item">
                            <a class="nav-link active" href="/">Wpisy</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="/stats">Statystyki</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="/accounts">Konta</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="/categories">Kategorie</a>
                          </li>
                      </ul>
                      <div>
                        <ul>
                          {% for account_cp in accounts_cp %}
                              <li>Konto: {{ account_cp.name }}</li>
                              <li>Saldo: {{ account_cp.cash_amount }} PLN</li>
                              Ostatnia operacja:
                              <p>{{ account_cp.entry_set.all.last.date }} --- {{ account_cp.entry_set.all.last.amount }}</p>
{#                                {% for entry_cp in entries_cp %}#}
{#                                    {% if account_cp.id == entry_cp.account.id %}#}
{#                                        <li>{{ entry_cp.date }} -- {{ entry_cp.amount }}</li>#}
{#                                    {% endif %}#}
{#                                {% endfor %}#}
                          {% endfor %}
                        </ul>
                      </div>
                    </nav>
                </div>
                <div class="col-9">
                    {% block content %}
                    {% endblock %}
                </div>
             </div>
        </section>
    </div>
{#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"#}
{#        crossorigin="anonymous"></script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

templates/generateSCR.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>App</title>
</head>
<body>
    <form action="#" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
    <button type="submit">Dodaj</button>
    </form>
</body>
</html>

templates/scheduleArr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <table>
        <tr><th>Rozkład</th><th>Numer rejsu</th><th>Kierunek</th><th></th></tr>
    {% for flight in schedule %}
        <tr><td>{{ flight.sibt }}</td><td>{{ flight.career }} {{ flight.arr_flight_number }}</td><td>{{ flight.origin }}</td></tr>
    {% endfor %}
    </table>
    <a href="/arrscr">Dodaj rejs</a>
</body>
</html>

templates/settings.html
{% extends 'base.html' %}
{% block content %}
    <h1>dodaj kategorię</h1>
    <h1>dodaj podkategorię</h1>
{% endblock %}

templates/stats.html
{% extends 'base.html' %}
{% block content %}
{% load poll_extras %}
    <div>
        <div>
            <canvas id="myChart"></canvas>
            <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
            <script>
            var ctx = document.getElementById('myChart');
            var chart = new Chart(ctx, {
            // The type of chart we want to create
            type: 'doughnut',

            // The data for our dataset
            data: {
                labels: [
                    {% for label in labels %}
                        '{{ label }}',
                    {% endfor %}
                ],
                datasets: [{
                    label: 'My First dataset',
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(0, 51, 0, 0.2)',
                        'rgba(153, 255, 153, 0.2)',
                        'rgba(0, 0, 153, 0.2)',
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(0, 51, 0, 1)',
                        'rgba(153, 255, 153, 1)',
                        'rgba(0, 0, 153, 2)',
                    ],
                    data: {{ data }}
                }]
            },

            // Configuration options go here
            options: {}
            });
            </script>
        </div>
        <div>
            <table>
                <thead>
                    <tr>
                        <th>Kategoria</th>
                        <th>Suma</th>
                    </tr>
                </thead>
                <tbody>
                    {% for key, value in ctx.items %}
                    <tr>
                        <td>{{ key }}</td>
                        <td>{{ value }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}